### ISSUE TITLE
Update changelog / add release for 2.0.0

### ISSUE THREAD

**Issue by voxpelli** [mysticatea/eslint-plugin-es#18]
The README states that one should check GitHub releases to find out what has changed in a release: https://github.com/mysticatea/eslint-plugin-es#-changelog

But there are no release notes written for `2.0.0`, so unless one looks at the commits there are no way to find out what motivated the major bump in version number. (A written release can also get picked up by tools like Renovate)

**Comment by mysticatea** [comment]
Thank you for pinging. I had forgotten it.

I have written: https://github.com/mysticatea/eslint-plugin-es/releases/tag/v2.0.0
