### ISSUE TITLE
`no-arrow-functions` --fix incorrectly converts async functions

### ISSUE THREAD

**Issue by anastasiagryshchenko** [mysticatea/eslint-plugin-es#20]
`async () => {}` is being automatically converted to synchronous functions by omitting the `async` before `function(){}`

**Comment by mysticatea** [comment]
I apologize for my late response. And thank you for your report.

I confirmed it. I will fix.

**Comment by anastasiagryshchenko** [comment]
no worries at all, thank you for looking into it!
