### ISSUE TITLE
Create optional rules for prototype methods

### ISSUE THREAD

**Issue by edg2s** [mysticatea/eslint-plugin-es#24]
I found your comment at explaining why these aren't available at the moment: https://github.com/mysticatea/eslint-plugin-es/pull/2#issuecomment-386864281. While it is true that you will get some false positives, many of the methods have unique enough names that most of the time you won't, and the rare cases that do can be fixed with an inline exception.

I suggest creating these rules and put them in separate rule groups so they are not enabled by default, but can be used when users are happy to deal with the small number of false positives.

We have a similar set of rules for Wikipedia at https://github.com/wikimedia/eslint-config-wikimedia/tree/master/language and would like to be able to use this library instead, but the prototype method rules are important to us and catch lots of issues.

**Comment by ota-meshi** [comment]
If you only need to report by property name, I think you can use the following rule as a workaround.

https://eslint.org/docs/rules/no-restricted-properties
