### ISSUE TITLE
Published package appears to be broken

### ISSUE THREAD

**Issue by smithalan92** [mysticatea/eslint-plugin-es#48]
Hi, I just installed eslint-plugin-es@3.0.1 which is the latest according to npm.

simple .eslintrc.js config

```
...
plugins: [
    'es',
  ],
rules: {
  'es/no-bigint': 'error',
  'es/no-dynamic-import': 'error',
},
...
```

Running `npx eslint .` , I got random loads of errors, eg. 

```
  1:1  error  Definition for rule 'es/no-export-ns-from' was not found                es/no-export-ns-from
  1:1  error  Definition for rule 'es/no-import-meta' was not found                   es/no-import-meta
  1:1  error  Definition for rule 'es/no-nullish-coalescing-operators' was not found  es/no-nullish-coalescing-operators
```

Examining `./node_modules/eslint-plugin-es/lib/index.js`  it doesn't appear any of these rules exist, they don't appear to be in `/lib/rules` either ?

**Comment by mysticatea** [comment]
Looks like you have the settings of those non-existent rules in your config. Remove those settings from your config.

On the other hand, install the latest version of this plugin because those rules were added at 4.0.0.
