### ISSUE TITLE
Object.entries

### ISSUE THREAD

**Issue by GarfieldDeepClone** [mysticatea/eslint-plugin-es#51]
Hi :)

In the rules.json I see:
`"entries": {
        "compatible": true,
        "alternative": "Object.entries()",
        "ES6": true
    },`

But I think Object.entries is not ES6/ECMA2015, it's ES8/ECMA2017

And it's also missing in this documentation?
https://www.npmjs.com/package/eslint-plugin-you-dont-need-lodash-underscore

**Comment by ota-meshi** [comment]
Hi.

(I'm not the maintainer, but let me comment.)

What is rules.json? I think `Object.entries` rule has already been categorized in ES2017.

https://github.com/mysticatea/eslint-plugin-es/blob/3d5938ef417e1093b22251850fb5fe99d3f41b20/lib/rules/no-object-entries.js#L13

If you're talking about the following link? If so, I think you may be reporting the wrong repository.

https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/blob/6942877375884d53c0fd1ef20c89f16884e57f7d/lib/rules/rules.json#L202

**Comment by GarfieldDeepClone** [comment]
You're totally right, posted at the wrong place.
